### ISSUE TITLE
Feature Request: Confg option to active "Tame" when in Creative Mode

### ISSUE THREAD

**Issue by PitchBright** [a3626a/HungryAnimals-1.8#2]
It would be a nice feature to be able to have all animals temporarily "Tame" while in Creative Mode. It's really hard to approach a Wild animal and use the debug glass, or nbtedit on them when they run away so fast. Since the mod is meant for Survival Mode play… it makes sense to have an option to "temporarily" make the animal behave as though it's tame, while we are in Creative Mode.

S: CreativeTame=True/False

Something like that. That way for users who do want animals to be wild/tame in Creative Mode, they can set it to False, and animals will behave normally.

When in Creative Mode, if you change gamemode back to Survival, the Animal behaves normal again.

**Comment by a3626a** [comment]
Debug glass in hotbar makes animals behave normally

(I'm just closing old issues)
