### ISSUE TITLE
Adding other mod's items to Animal Drops causes crash on startup

### ISSUE THREAD

**Issue by PitchBright** [a3626a/HungryAnimals-1.8#3]
When I add other mod's items that the vanilla animals should drop when they are killed… the game crashes. For example if I want to make Cows drop "Hide" from "Lot's of Mobs" (instead of Vanilla Leather), or Sheep drop "Mutton" from Pam's Harvestcraft… it doesn't work.

The problem seems to occur on the two sections:

    S:"Ability: items drops that the amount is decided by hunger value" <
     >
    S:"Ability: items drops that the amount is decided randomly" <
     >

**Comment by PitchBright** [comment]
This is for 1.7.10 alpha3

**Comment by a3626a** [comment]
can you give me the crash report?
I (maybe) fixed it in alpha05, try it. but i'm not sure. I need the crash report.

**Comment by a3626a** [comment]
Okay, try alpha5.
I'm not sure whether the bug is fixed or not. But I'm sure that your minecraft will not crash. This will print a log about the configuration error.

**Comment by a3626a** [comment]
Finally, try alpha6.
In previous versions, if Hungry Animals mod is loaded before some other mods(especially Pam's Harvestcraft, LOM is always loaded before HA.) HA can't find the item in the configuration file and it crashes.
Anyway, it is fixed. Plz check

**Comment by PitchBright** [comment]
I'll test it out for sure. But I should also mention that when I tried the LOM Hide (and not the Pams Mutton)… in Alpha3, it didn't work. Are you sure that LOM loads before HA?

**Comment by a3626a** [comment]
Yes, lom loads before HA. Honestly, my config is loaded before LOM. Anyway, it's fixed

**Comment by PitchBright** [comment]
Confirmed fixed.
