### ISSUE TITLE
Client crash while trying to render poo states using version 1.8-2.1-alpha03

### ISSUE THREAD

**Issue by kreezxil** [a3626a/HungryAnimals-1.8#5]
client crash report: http://paste.ee/p/jNN3W

client FML latest log: https://gist.github.com/kreezxil/b25271e8e8af878011fa

I noticed you referenced alpha-04 to another issue poster, however, I didn't see alpha04 in your dropbox.

**Comment by a3626a** [comment]
Fixed it.

Thank you for your report
