### ISSUE TITLE
Feature Request: Option to disable the GUI and the Particles in config

### ISSUE THREAD

**Issue by PitchBright** [a3626a/HungryAnimals-1.8#7]
Feature Request: Option to disable the GUI and the Particles in config

**Comment by a3626a** [comment]
1. I'm planning to add option for the overlay (that appears hovering mouse on an animal) ; it could be config / option / command. 

2. Which particle do you mean?

**Comment by PitchBright** [comment]
The coloured particles that tell you if the animal is growing or is sick, etc.

**Comment by a3626a** [comment]
That particles are sorts of potion particles. It's complicated to disable potion particle effect. I won't do this work soon. There are many other things to be solved first.

**Comment by PitchBright** [comment]
Oh, the animals have potion effects on them?
